name: Build KivyMD APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # changed to latest for faster allocation

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            openjdk-17-jdk \
            unzip \
            zip \
            libncurses5 \
            libncurses5-dev \
            libtinfo5 \
            python3-pip

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/package.name = .*/package.name = MyApp/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.example/' buildozer.spec
          sed -i 's/# (str) Application versioning .*/version = 0.1/' buildozer.spec
          sed -i 's/# (list) Application requirements .*/requirements = python3,kivy==2.2.1,kivymd,requests,plyer/' buildozer.spec
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
