name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk unzip
          pip install --upgrade pip
          pip install buildozer cython==0.29.36 virtualenv

      - name: Build APK
        run: |
          buildozer init
          sed -i 's/^# requirements = python3/requirements = python3,kivy,kivymd,requests,plyer,geocoder/' buildozer.spec
          sed -i 's/^# (str) Application title/Application title/' buildozer.spec
          sed -i 's/^title = My Application/title = Blood Donation App/' buildozer.spec
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: bin/*.apk
