name: Build KivyMD APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04   # ✅ Updated runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # ✅ Install system dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip unzip \
            openjdk-17-jdk \
            python3-pip \
            python3-setuptools \
            python3-wheel \
            python3-venv \
            libffi-dev \
            libssl-dev \
            libsqlite3-dev \
            zlib1g-dev \
            libncurses5 \
            libtinfo5 \
            pkg-config

      # ✅ Install Buildozer
      - name: Install buildozer
        run: |
          pip install --upgrade pip Cython buildozer

      # ✅ Setup Android SDK + NDK
      - name: Setup Android SDK & NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          curl -fo sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d latest
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --install \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0" \
            "ndk;21.4.7075529"

      # ✅ Initialize buildozer.spec if missing
      - name: Ensure buildozer.spec
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
            sed -i 's/package.name = .*/package.name = MyApp/' buildozer.spec
            sed -i 's/package.domain = .*/package.domain = org.example/' buildozer.spec
            sed -i 's/# (str) Application versioning .*/version = 0.1/' buildozer.spec
            sed -i 's/# (list) Application requirements .*/requirements = python3,kivy==2.2.1,kivymd,requests,plyer/' buildozer.spec
          fi

      # ✅ Build APK
      - name: Build APK
        env:
          ANDROIDSDK: $HOME/android-sdk
          ANDROIDNDK: $HOME/android-sdk/ndk/21.4.7075529
          PATH: $HOME/android-sdk/platform-tools:$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        run: |
          buildozer android debug

      # ✅ Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: MyApp-APK
          path: bin/*.apk
